p8105\_hw1\_cl4043
================
Stella Li

This is my solution to HW1.

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──

    ## ✓ ggplot2 3.3.2     ✓ purrr   0.3.4
    ## ✓ tibble  3.0.3     ✓ dplyr   1.0.2
    ## ✓ tidyr   1.1.2     ✓ stringr 1.4.0
    ## ✓ readr   1.3.1     ✓ forcats 0.5.0

    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

## Problem 1

Create a data frame with the specified elements.

``` r
prob1_df = 
  tibble(
    samp = rnorm(10),
    samp_gt_0 = samp > 0,
    char_vec = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j"),
    factor_vec = factor(c("low", "low", "low", "mod", "mod", "mod", "mod", "high", "high", "high"))
  )
```

Take the mean of each variable in my data frame.

``` r
mean(pull(prob1_df, samp))
```

    ## [1] -0.1802878

``` r
mean(pull(prob1_df, samp_gt_0))
```

    ## [1] 0.5

``` r
mean(pull(prob1_df, char_vec))
```

    ## Warning in mean.default(pull(prob1_df, char_vec)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

``` r
mean(pull(prob1_df, factor_vec))
```

    ## Warning in mean.default(pull(prob1_df, factor_vec)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

I can take the mean of numbers and logical but not character or factor.

``` r
as.numeric(pull(prob1_df, samp))
```

    ##  [1] -1.434868440 -0.011419092  0.795575445  0.809842072  0.747849094
    ##  [6] -1.414343312  0.006974991 -1.808664665  0.836265724 -0.330089893

``` r
as.numeric(pull(prob1_df, samp_gt_0))
```

    ##  [1] 0 0 1 1 1 0 1 0 1 0

``` r
as.numeric(pull(prob1_df, char_vec))
```

    ## Warning: NAs introduced by coercion

    ##  [1] NA NA NA NA NA NA NA NA NA NA

``` r
as.numeric(pull(prob1_df, factor_vec))
```

    ##  [1] 2 2 2 3 3 3 3 1 1 1

as.numeric function tries to convert all objects into numeric values
which do not work on character vectors, and will turn logical vectors
into 0 and 1, and factor vectors into different numbers according to the
level of factor.

``` r
# convert the logical vector to numeric, and multiply the random sample by the result
as.numeric(pull(prob1_df, samp_gt_0)) * pull(prob1_df, samp)
```

    ##  [1] 0.000000000 0.000000000 0.795575445 0.809842072 0.747849094 0.000000000
    ##  [7] 0.006974991 0.000000000 0.836265724 0.000000000

``` r
# convert the logical vector to a factor, and multiply the random sample by the result
as.factor(pull(prob1_df, samp_gt_0)) * pull(prob1_df, samp)
```

    ## Warning in Ops.factor(as.factor(pull(prob1_df, samp_gt_0)), pull(prob1_df, : '*'
    ## not meaningful for factors

    ##  [1] NA NA NA NA NA NA NA NA NA NA

``` r
# convert the logical vector to a factor and then convert the result to numeric, and multiply the random sample by the result
as.numeric(as.factor(pull(prob1_df, samp_gt_0))) * pull(prob1_df, samp)
```

    ##  [1] -1.43486844 -0.01141909  1.59115089  1.61968414  1.49569819 -1.41434331
    ##  [7]  0.01394998 -1.80866466  1.67253145 -0.33008989

## Problem 2

``` r
data("penguins", package = "palmerpenguins")
```

``` r
names(penguins)
```

    ## [1] "species"           "island"            "bill_length_mm"   
    ## [4] "bill_depth_mm"     "flipper_length_mm" "body_mass_g"      
    ## [7] "sex"               "year"

There are 8 variables in this dataset, including “species”, “island”,
“bill\_length\_mm”, “bill\_depth\_mm”, “flipper\_length\_mm”,
“body\_mass\_g”, “sex”, and “year”. Important values include the
length and the depth of the bill, the length of the flipper, the body
mass, the species, and the sex of the penguins, the island and the year
in which the data was collected.

``` r
ncol(penguins)
```

    ## [1] 8

``` r
nrow(penguins)
```

    ## [1] 344

There are 8 columns and 344 rows in total.

``` r
mean(penguins$flipper_length_mm, na.rm = TRUE)
```

    ## [1] 200.9152

The mean of the flipper length is 200.9152 mm.

``` r
penguin_plot <- ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm)) + 
  geom_point(aes(color = species))

penguin_plot
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

![](p8105_hw1_cl4043_files/figure-gfm/plot-1.png)<!-- -->

``` r
ggsave("penguin_plot.png", width = 5, height = 4)
```

    ## Warning: Removed 2 rows containing missing values (geom_point).
